onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_spi_ctrl/clk
add wave -noupdate /tb_spi_ctrl/rst_n
add wave -noupdate /tb_spi_ctrl/spi_en
add wave -noupdate /tb_spi_ctrl/start
add wave -noupdate /tb_spi_ctrl/sclk_tick
add wave -noupdate /tb_spi_ctrl/tx_data_valid
add wave -noupdate /tb_spi_ctrl/tx_data
add wave -noupdate /tb_spi_ctrl/start_bit_det
add wave -noupdate /tb_spi_ctrl/parity_error
add wave -noupdate /tb_spi_ctrl/stop_error
add wave -noupdate /tb_spi_ctrl/start_bit_en
add wave -noupdate /tb_spi_ctrl/stop_bit_en
add wave -noupdate /tb_spi_ctrl/rx_enable
add wave -noupdate /tb_spi_ctrl/tx_enable
add wave -noupdate /tb_spi_ctrl/serial_clk
add wave -noupdate /tb_spi_ctrl/msb_first
add wave -noupdate /tb_spi_ctrl/parity_mode
add wave -noupdate /tb_spi_ctrl/data_bits
add wave -noupdate /tb_spi_ctrl/data_out
add wave -noupdate /tb_spi_ctrl/busy
add wave -noupdate /tb_spi_ctrl/done
add wave -noupdate /tb_spi_ctrl/serial_in
add wave -noupdate /tb_spi_ctrl/serial_out
add wave -noupdate /tb_spi_ctrl/data_in
add wave -noupdate /tb_spi_ctrl/i
add wave -noupdate /tb_spi_ctrl/exp
add wave -noupdate /tb_spi_ctrl/got
add wave -noupdate /tb_spi_ctrl/u_ctrl/clk
add wave -noupdate /tb_spi_ctrl/u_ctrl/rst_n
add wave -noupdate /tb_spi_ctrl/u_ctrl/spi_en
add wave -noupdate /tb_spi_ctrl/u_ctrl/start
add wave -noupdate /tb_spi_ctrl/u_ctrl/sclk_tick
add wave -noupdate /tb_spi_ctrl/u_ctrl/tx_data_valid
add wave -noupdate /tb_spi_ctrl/u_ctrl/tx_data
add wave -noupdate /tb_spi_ctrl/u_ctrl/start_bit_det
add wave -noupdate /tb_spi_ctrl/u_ctrl/parity_error
add wave -noupdate /tb_spi_ctrl/u_ctrl/stop_error
add wave -noupdate /tb_spi_ctrl/u_ctrl/start_bit_en
add wave -noupdate /tb_spi_ctrl/u_ctrl/stop_bit_en
add wave -noupdate /tb_spi_ctrl/u_ctrl/rx_enable
add wave -noupdate /tb_spi_ctrl/u_ctrl/tx_enable
add wave -noupdate /tb_spi_ctrl/u_ctrl/serial_clk
add wave -noupdate /tb_spi_ctrl/u_ctrl/msb_first
add wave -noupdate /tb_spi_ctrl/u_ctrl/parity_mode
add wave -noupdate /tb_spi_ctrl/u_ctrl/data_bits
add wave -noupdate /tb_spi_ctrl/u_ctrl/data_out
add wave -noupdate /tb_spi_ctrl/u_ctrl/busy
add wave -noupdate /tb_spi_ctrl/u_ctrl/done
add wave -noupdate /tb_spi_ctrl/u_ctrl/state
add wave -noupdate /tb_spi_ctrl/u_ctrl/next_state
add wave -noupdate /tb_spi_ctrl/u_ctrl/bit_cnt
add wave -noupdate /tb_spi_ctrl/u_ctrl/tx_reg
add wave -noupdate /tb_spi_ctrl/u_dp/clk
add wave -noupdate /tb_spi_ctrl/u_dp/n_rst
add wave -noupdate /tb_spi_ctrl/u_dp/serial_in
add wave -noupdate /tb_spi_ctrl/u_dp/start_bit_en
add wave -noupdate /tb_spi_ctrl/u_dp/stop_bit_en
add wave -noupdate /tb_spi_ctrl/u_dp/rx_enable
add wave -noupdate /tb_spi_ctrl/u_dp/serial_clk
add wave -noupdate /tb_spi_ctrl/u_dp/tx_enable
add wave -noupdate /tb_spi_ctrl/u_dp/msb_first
add wave -noupdate /tb_spi_ctrl/u_dp/parity_mode
add wave -noupdate /tb_spi_ctrl/u_dp/data_bits
add wave -noupdate /tb_spi_ctrl/u_dp/data_out
add wave -noupdate /tb_spi_ctrl/u_dp/start_bit_det
add wave -noupdate /tb_spi_ctrl/u_dp/parity_error
add wave -noupdate /tb_spi_ctrl/u_dp/stop_error
add wave -noupdate /tb_spi_ctrl/u_dp/serial_out
add wave -noupdate /tb_spi_ctrl/u_dp/data_in
add wave -noupdate /tb_spi_ctrl/u_dp/state
add wave -noupdate /tb_spi_ctrl/u_dp/next_state
add wave -noupdate /tb_spi_ctrl/u_dp/data_bit_cnt
add wave -noupdate /tb_spi_ctrl/u_dp/next_data_bit_cnt
add wave -noupdate /tb_spi_ctrl/u_dp/serial_in_reg
add wave -noupdate /tb_spi_ctrl/u_dp/parallel_in
add wave -noupdate /tb_spi_ctrl/u_dp/next_parallel_in
add wave -noupdate /tb_spi_ctrl/u_dp/parity_bit
add wave -noupdate /tb_spi_ctrl/u_dp/next_parity_bit
add wave -noupdate /tb_spi_ctrl/u_dp/stop_bit
add wave -noupdate /tb_spi_ctrl/u_dp/next_stop_bit
add wave -noupdate /tb_spi_ctrl/u_dp/shift_out
add wave -noupdate /tb_spi_ctrl/u_dp/next_shift_out
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {118968 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {118968 ps} {119091 ps}
